"""baseline schema

Revision ID: 484de2eac020
Revises: 
Create Date: 2026-07-16 22:41:27.092895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '484de2eac020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('long_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('earn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_paid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('members', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claims', sa.Integer(), nullable=False),
    sa.Column('expiry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # FK to merchant added after all tables exist (cyclic dependency — see below).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # FK to merchantapplication added after all tables exist (cyclic dependency).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_email'), 'merchant', ['email'], unique=True)
    op.create_table('merchantapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cashback_rate', sa.Float(), nullable=False),
    sa.Column('markets', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revenue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orders', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aov', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goals', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('heard', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    # FK to campaign added after all tables exist (cyclic dependency).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instagram_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('campaignsubmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('long_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('earn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaignsubmission_merchant_id'), 'campaignsubmission', ['merchant_id'], unique=False)
    op.create_table('dealevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealevent_campaign_id'), 'dealevent', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dealevent_kind'), 'dealevent', ['kind'], unique=False)
    op.create_table('mention',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_user_id'), 'mention', ['user_id'], unique=False)
    op.create_table('merchantmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_by_admin', sa.Boolean(), nullable=False),
    sa.Column('read_by_merchant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchantmessage_merchant_id'), 'merchantmessage', ['merchant_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('image_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_post_id'), 'receipt', ['post_id'], unique=False)
    op.create_index(op.f('ix_receipt_user_id'), 'receipt', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # campaign <-> merchant <-> merchantapplication form a foreign-key cycle, so
    # these three FKs can't be declared inline (a table would reference one that
    # doesn't exist yet). Add them now that every table exists. Skipped on SQLite,
    # which can't ALTER TABLE ADD CONSTRAINT and doesn't enforce FKs here anyway.
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key("fk_campaign_merchant_id", "campaign",
                              "merchant", ["merchant_id"], ["id"])
        op.create_foreign_key("fk_merchant_application_id", "merchant",
                              "merchantapplication", ["application_id"], ["id"])
        op.create_foreign_key("fk_merchantapplication_campaign_id", "merchantapplication",
                              "campaign", ["campaign_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the cyclic FKs first so the tables can be dropped (Postgres only).
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_merchantapplication_campaign_id", "merchantapplication", type_="foreignkey")
        op.drop_constraint("fk_merchant_application_id", "merchant", type_="foreignkey")
        op.drop_constraint("fk_campaign_merchant_id", "campaign", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_user_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_post_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_merchantmessage_merchant_id'), table_name='merchantmessage')
    op.drop_table('merchantmessage')
    op.drop_index(op.f('ix_mention_user_id'), table_name='mention')
    op.drop_table('mention')
    op.drop_index(op.f('ix_dealevent_kind'), table_name='dealevent')
    op.drop_index(op.f('ix_dealevent_campaign_id'), table_name='dealevent')
    op.drop_table('dealevent')
    op.drop_index(op.f('ix_campaignsubmission_merchant_id'), table_name='campaignsubmission')
    op.drop_table('campaignsubmission')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('merchantapplication')
    op.drop_index(op.f('ix_merchant_email'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_table('campaign')
    op.drop_table('adminactivity')
    # ### end Alembic commands ###
